/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Add structured data to help search engines understand the content of your page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SchemaMarkup".
 */
export type SchemaMarkup =
  | {
      jsonLD:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    hero: HeroBlock;
    richtext: RichtextBlock;
    'terminal-block': TerminalBlockBlock;
    'card-grid': CardGridBlock;
    'collection-list': CollectionListBlock;
    contact: ContactBlock;
    'entry-list': EntryListBlock;
    equalizer: EqualizerBlock;
  };
  collections: {
    users: User;
    media: Media;
    pages: Page;
    projects: Project;
    blogs: Blog;
    tags: Tag;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'pages';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    siteConfig: SiteConfig;
    layout: Layout;
  };
  globalsSelect: {
    siteConfig: SiteConfigSelect<false> | SiteConfigSelect<true>;
    layout: LayoutSelect<false> | LayoutSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  kicker?: string | null;
  size: 'large' | 'default';
  heading: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichtextBlock".
 */
export interface RichtextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richtext';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TerminalBlockBlock".
 */
export interface TerminalBlockBlock {
  lines: {
    type: 'command' | 'output';
    command?: string | null;
    output?: string | null;
    indent?: boolean | null;
    id?: string | null;
  }[];
  systemNodes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'terminal-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  content?: (NumberedGridBlock | CellGridBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'card-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedGridBlock".
 */
export interface NumberedGridBlock {
  heading?: string | null;
  cards: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'numbered-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CellGridBlock".
 */
export interface CellGridBlock {
  swap?: boolean | null;
  items: {
    type: 'text' | 'stack';
    heading?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    stackItems?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    footnote?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'cell-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionListBlock".
 */
export interface CollectionListBlock {
  source: 'projects' | 'blogs';
  id?: string | null;
  blockName?: string | null;
  blockType: 'collection-list';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  infoHeading?: string | null;
  infoDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  email: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryListBlock".
 */
export interface EntryListBlock {
  entries: {
    label: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'entry-list';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EqualizerBlock".
 */
export interface EqualizerBlock {
  track?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'equalizer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  hash: string;
  dataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * The name of the page
   */
  title: string;
  /**
   * The slug is used in the URL for this page. It's recommended to keep it short and descriptive.
   */
  slug: string;
  blocksTab?: {
    /**
     * Add and arrange content blocks to build the page.
     */
    blocks?:
      | (
          | CardGridBlock
          | CollectionListBlock
          | ContactBlock
          | EntryListBlock
          | EqualizerBlock
          | HeroBlock
          | RichtextBlock
          | TerminalBlockBlock
        )[]
      | null;
  };
  localSeoTab: LocalSeoTab;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocalSeoTab".
 */
export interface LocalSeoTab {
  /**
   * SEO title for this page. If not provided, it will fall back to a suitable document property (e.g., the page title)
   */
  title?: string | null;
  /**
   * SEO description for this page.
   */
  description?: string | null;
  /**
   * Open Graph image for this page's URL.
   */
  image?: (string | null) | Media;
  /**
   * If not provided it will be a self-referencing URL.
   */
  cannoical?: string | null;
  /**
   * Redirect URL for this page. Please start with https://
   */
  redirect?: string | null;
  keywords?: string | null;
  /**
   * Configure how search engines interact with this page.
   */
  robotsConfig: {
    /**
     * Turn ON to prevent this page from showing up in search engine results.
     */
    disableIndex: boolean;
    /**
     * Turn ON to prevent search engines from following links on this page.
     */
    disableFollow: boolean;
    /**
     * Turn ON to prevent search engines from indexing images on this page.
     */
    disableImageIndex: boolean;
    /**
     * Turn ON to prevent search engines from displaying a snippet of this page in search results.
     */
    disableSnippet: boolean;
  };
  schemaMarkup?: SchemaMarkup;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'pages';
          value: string | Page;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'pages'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  /**
   * The slug is used in the URL for this page. It's recommended to keep it short and descriptive.
   */
  slug: string;
  localSeoTab: LocalSeoTab;
  meta: {
    tags?: (string | Tag)[] | null;
    techStack?: string[] | null;
    description: string;
    kicker?: string | null;
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    outcomeStats?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  title: string;
  /**
   * The slug is used in the URL for this page. It's recommended to keep it short and descriptive.
   */
  slug: string;
  localSeoTab: LocalSeoTab;
  meta: {
    tags?: (string | Tag)[] | null;
    trackNumber?: number | null;
    publishedDate: string;
    excerpt: string;
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  hash?: T;
  dataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocksTab?:
    | T
    | {
        blocks?: T | {};
      };
  localSeoTab?: T | LocalSeoTabSelect<T>;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocalSeoTab_select".
 */
export interface LocalSeoTabSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  cannoical?: T;
  redirect?: T;
  keywords?: T;
  robotsConfig?:
    | T
    | {
        disableIndex?: T;
        disableFollow?: T;
        disableImageIndex?: T;
        disableSnippet?: T;
      };
  schemaMarkup?: T | SchemaMarkupSelect<T>;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SchemaMarkup_select".
 */
export interface SchemaMarkupSelect<T extends boolean = true> {
  jsonLD?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  localSeoTab?: T | LocalSeoTabSelect<T>;
  meta?:
    | T
    | {
        tags?: T;
        techStack?: T;
        description?: T;
        kicker?: T;
        body?: T;
        outcomeStats?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  localSeoTab?: T | LocalSeoTabSelect<T>;
  meta?:
    | T
    | {
        tags?: T;
        trackNumber?: T;
        publishedDate?: T;
        excerpt?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteConfig".
 */
export interface SiteConfig {
  id: string;
  globalSeoTab: GlobalSeoTab;
  tracking?: {
    googleTagManagerID?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GlobalSeoTab".
 */
export interface GlobalSeoTab {
  /**
   * Default Open Graph image for the site.
   */
  image?: (string | null) | Media;
  /**
   * Override robot configuration for all pages on the site.
   */
  robotsConfig: {
    /**
     * Turn ON to prevent this page from showing up in search engine results.
     */
    disableIndex: boolean;
    /**
     * Turn ON to prevent search engines from following links on this page.
     */
    disableFollow: boolean;
    /**
     * Turn ON to prevent search engines from indexing images on this page.
     */
    disableImageIndex: boolean;
    /**
     * Turn ON to prevent search engines from displaying a snippet of this page in search results.
     */
    disableSnippet: boolean;
  };
  schemaMarkup?: SchemaMarkup;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout".
 */
export interface Layout {
  id: string;
  header?: IPayloadHeader;
  footer?: IPayloadFooter;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IPayloadHeader".
 */
export interface IPayloadHeader {
  title?: string | null;
  links?:
    | {
        link: Link;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Link".
 */
export interface Link {
  label?: string | null;
  type: 'external' | 'internal';
  url?: string | null;
  reference?: {
    relationTo: 'pages';
    value: string | Page;
  } | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IPayloadFooter".
 */
export interface IPayloadFooter {
  copyright?: string | null;
  links?:
    | {
        link: Link;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteConfig_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  globalSeoTab?: T | GlobalSeoTabSelect<T>;
  tracking?:
    | T
    | {
        googleTagManagerID?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GlobalSeoTab_select".
 */
export interface GlobalSeoTabSelect<T extends boolean = true> {
  image?: T;
  robotsConfig?:
    | T
    | {
        disableIndex?: T;
        disableFollow?: T;
        disableImageIndex?: T;
        disableSnippet?: T;
      };
  schemaMarkup?: T | SchemaMarkupSelect<T>;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout_select".
 */
export interface LayoutSelect<T extends boolean = true> {
  header?: T | IPayloadHeaderSelect<T>;
  footer?: T | IPayloadFooterSelect<T>;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IPayloadHeader_select".
 */
export interface IPayloadHeaderSelect<T extends boolean = true> {
  title?: T;
  links?:
    | T
    | {
        link?: T | LinkSelect<T>;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Link_select".
 */
export interface LinkSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  url?: T;
  reference?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IPayloadFooter_select".
 */
export interface IPayloadFooterSelect<T extends boolean = true> {
  copyright?: T;
  links?:
    | T
    | {
        link?: T | LinkSelect<T>;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}